# Generated by Django 5.0.2 on 2024-02-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SILCGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the SILC group.', max_length=200)),
                ('location', models.CharField(help_text='The physical location where the group meets.', max_length=300)),
                ('date_started', models.DateField(help_text='The date when the group began operation.')),
                ('email', models.EmailField(help_text='Contact email for the group.', max_length=254)),
                ('contact_number', models.CharField(help_text='Contact phone number for the group.', max_length=15)),
            ],
        ),
    ]
